### ISSUE TITLE
On the test appliance setup, already migrated user is redirected to wrong link

### ISSUE THREAD

**Issue by encius** [expressly/magento#17]
On: https://expressly-local.com/magento-1.9.2.4/

If user was already migrated, following message is returned: "Your email address has already been registered on this store. Please login with your credentials. Pressing OK will redirect you to the login page."
Pressing OK redirects to http://expressly-local.com/my-account/ which returns 404

**Comment by mgsmith57** [comment]
Fixed in 2.5.0
